### ISSUE TITLE
code for CSP

### ISSUE THREAD

**Issue by weizhenhit** [youngeun1209/NeuroTalk#3]
Is it possible to provide the code for CSP? Without this code, it's hard to reproduce the whole article. Thanks!

**Comment by youngeun1209** [comment]
Yes. I re-uploaded. And you can use BBCI toolbox to use it.

**Comment by samin9796** [comment]
@1180300318 Hi! I just would like to ask whether you could extract the CSP features using the provided code. I am facing some issues with feature extraction. Thank you in advance.

**Comment by youngeun1209** [comment]
Hi.
I uploaded the multi CSP code from BBCI toolbox. The version of the BBCI toolbox I have might be different. 
I hope this is helpful for you.

**Comment by samin9796** [comment]
@youngeun1209 Thank you so much for uploading the multi CSP code! 

Now I am getting an error on this line - 

`y_dec{dd} = find(epo.y_dec==dd);`

It looks like epo is a structure and you are accessing the y_dec field which contains the class labels. I have EEG data in cnt, fdt and set formats but not in epo structure. If it is possible to share a subset of the dataset in epo format or any script to convert from cnt/fdt/set to epo that you used, that would be great! I am not that familiar with matlab, so I am sorry if I am missing something here.
