### ISSUE TITLE
Where is the pretrained model?

### ISSUE THREAD

**Issue by qwerdfjklol** [youngeun1209/NeuroTalk#4]
Hello, I'm trying to evaluate the model using the sample data you provided. But there's no pretrained madel for the GAN. The only pretrained model you provided  in README.md is the pretrained vocoder.

**Comment by MJy1023** [comment]
The same problem. Could you please provide a complete version including all pretrained models mentioned in the essay. Much appreciation!

**Comment by youngeun1209** [comment]
I re-uploaded. Please check the google drive again!
