### ISSUE TITLE
After CSP

### ISSUE THREAD

**Issue by hanbuck30** [youngeun1209/NeuroTalk#7]
CSP successfully completed it. After that, in creating the dataset, I saw that the sample data you provided were by class (104,16). After vector_embedding, you can check the results by trials, not by each class. For example, if it was class 'yes', would it be mean after summing all the results corresponding to 'yes'?

**Comment by youngeun1209** [comment]
I'm not sure if I fully understood your question, but our model generates results on a per-trial basis and computes them using the corresponding ground truth for each word.
